services:

  web-ui:
    depends_on:
      - user-links
    build:
      context: ./web-ui/.
    container_name: web-ui
    networks:
      - link-share-net
    ports:
      - "8080:8080"

  user-links:
    depends_on:
      - user-links-db
    build:
      context: ./user-links/.
    container_name: user-links
    networks:
      - link-share-net
    environment:
      - POSTGRES_PASSWORD=${LINK_SHARE_DB_SUPERUSER:?database password not set}

  user-links-db:
    image: postgres:18.4
    container_name: user-links-db
    networks:
      - link-share-net
    environment:
      POSTGRES_PASSWORD: ${LINK_SHARE_DB_PASSWORD:?database password not set}
    volumes:
      - user-links-volume:/var/lib/postgresql

volumes:
  user-links-volume:

networks:
  link-share-net:
    driver: bridge
